### ISSUE TITLE
Does Linner support OS X 10.11?

### ISSUE THREAD

**Issue by kavlez** [SaitoWu/linner#48]
it works well on 10.10.
but on 10.11 , after I run ```linner w``` and reload my page , my browser console shows errors as below:

> vendor.js:10284 Uncaught TypeError: templateSpec.call is not a functionDomUtils.simulateClick @ dom_utils.js:243

**Comment by SaitoWu** [comment]
Oh, It my fault.

Linner was upgraded the handlebars version to v4.x, but the default templates are missed to upgrade.

So, the simple way to make it work is update the handlebars version in `config.yml`

```bash
http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars.runtime-v4.0.5.js
```

I'll release a new version later.

Have a good day! 🚀🚀 🚀

**Comment by kavlez** [comment]
Thank you @SaitoWu .This worked for me as well.
